//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempRecords
    {
        public int Id { get; set; }
        public double temperature { get; set; }
        public string location { get; set; }
        public string time { get; set; }
        public string date { get; set; }
    }
}
